package cn.hongchengq;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.json.JsonReadFeature;
import com.fasterxml.jackson.databind.json.JsonMapper;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

import java.io.File;

@Slf4j
public class Config {
    @Getter private static ConfigBean config;
    public static class ConfigBean {
        int gameVersion = 100;  // proto对应游戏版本 标记用

        // 启动模式 四种
        // 0：分割(将一个大proto根据message分割为各个单独的文件)
        // 1：分割(讲一个大proto根据先前定义的类型分割为几个文件)
        // 10：合并(根据message分割的文件合并为一个大proto)
        // 11：合并(根据类型分割的文件合并为一个大proto)
        int bootMode = 0;

        String mappingFilePath = "proto_test/550/autogenerated/mapping.tsv";    // 映射文件路径
        String inputProtoFilePath = "proto_test/550/clean/最原始的.proto";  // 原始proto文件路径
        String outputProtoFilePath = "proto_test/550/autogenerated/all.proto";  // 原始proto文件路径
    }

    // 初始化方法 加载config
    public static void JsonLoader() {
        JsonFactory jsonFactory = JsonFactory.builder()
                .configure(JsonReadFeature.ALLOW_JAVA_COMMENTS, true)// 配置特性
                .configure(JsonReadFeature.ALLOW_TRAILING_COMMA, true)// 配置特性
                .build();
        JsonMapper jsonMapper = new JsonMapper(jsonFactory);

        try {
            File file = new File("config.json");
            config = jsonMapper.readValue(file, ConfigBean.class);
        } catch (Exception e) {
            log.error("解析 config.json 失败", e);
        }
    }
}
